// Generated by scripts/generate_avarra_cpp.py; do not edit by hand.
#include "indoru/region_content.hpp"

#include <algorithm>
#include <array>

namespace indoru::world::content {
namespace {

constexpr std::array<CountryContent, 20> kCountries{{
    CountryContent{"country-001", "Avenra", "AVR", "flag-avenra", "assets/flags/flag-avenra.svg"},
    CountryContent{"country-002", "Solvani", "AVR", "flag-solvani", "assets/flags/flag-solvani.svg"},
    CountryContent{"country-003", "Mirqara", "AVR", "flag-mirqara", "assets/flags/flag-mirqara.svg"},
    CountryContent{"country-004", "Tavresh", "AVR", "flag-tavresh", "assets/flags/flag-tavresh.svg"},
    CountryContent{"country-005", "Orvessa", "AVR", "flag-orvessa", "assets/flags/flag-orvessa.svg"},
    CountryContent{"country-006", "Narevia", "AVR", "flag-narevia", "assets/flags/flag-narevia.svg"},
    CountryContent{"country-007", "Belqorin", "AVR", "flag-belqorin", "assets/flags/flag-belqorin.svg"},
    CountryContent{"country-008", "Yalmera", "AVR", "flag-yalmera", "assets/flags/flag-yalmera.svg"},
    CountryContent{"country-009", "Kadrune", "AVR", "flag-kadrune", "assets/flags/flag-kadrune.svg"},
    CountryContent{"country-010", "Eshvara", "AVR", "flag-eshvara", "assets/flags/flag-eshvara.svg"},
    CountryContent{"country-011", "Ruvessa", "AVR", "flag-ruvessa", "assets/flags/flag-ruvessa.svg"},
    CountryContent{"country-012", "Dalmor", "AVR", "flag-dalmor", "assets/flags/flag-dalmor.svg"},
    CountryContent{"country-013", "Virelune", "AVR", "flag-virelune", "assets/flags/flag-virelune.svg"},
    CountryContent{"country-014", "Qamrith", "AVR", "flag-qamrith", "assets/flags/flag-qamrith.svg"},
    CountryContent{"country-015", "Senvara", "AVR", "flag-senvara", "assets/flags/flag-senvara.svg"},
    CountryContent{"country-016", "Torvane", "AVR", "flag-torvane", "assets/flags/flag-torvane.svg"},
    CountryContent{"country-017", "Ilvarra", "AVR", "flag-ilvarra", "assets/flags/flag-ilvarra.svg"},
    CountryContent{"country-018", "Meskora", "AVR", "flag-meskora", "assets/flags/flag-meskora.svg"},
    CountryContent{"country-019", "Arqessa", "AVR", "flag-arqessa", "assets/flags/flag-arqessa.svg"},
    CountryContent{"country-020", "Venqara", "AVR", "flag-venqara", "assets/flags/flag-venqara.svg"},
}};

constexpr std::array<SettlementContent, 36> kSettlements{{
    SettlementContent{"settlement-001", "Navaar", "country-001", "region-avarra-crescent", SettlementType::Capital, "capital", "River capital, civic administration and national trade hub"},
    SettlementContent{"settlement-002", "Solmera", "country-002", "region-avarra-crescent", SettlementType::MajorCity, "major_city", "Sun-coast finance, media and regional passenger gateway"},
    SettlementContent{"settlement-003", "Mirqara Prime", "country-003", "region-avarra-crescent", SettlementType::MajorCity, "major_city", "Inland-sea port, wholesale markets and freight exchange"},
    SettlementContent{"settlement-007", "Arela", "country-004", "region-avarra-crescent", SettlementType::NormalCity, "normal_city", "Terraced-farm service centre with a restored hill citadel"},
    SettlementContent{"settlement-014", "Havora", "country-005", "region-avarra-crescent", SettlementType::NormalCity, "normal_city", "Western coastal city with a working harbor and beach districts"},
    SettlementContent{"settlement-021", "Orela", "country-006", "region-avarra-crescent", SettlementType::NormalCity, "normal_city", "Delta city shaped by canals, river freight and floodable parks"},
    SettlementContent{"settlement-028", "Vareka", "country-007", "region-avarra-crescent", SettlementType::NormalCity, "normal_city", "Limestone highland city with quarry, craft and construction trades"},
    SettlementContent{"settlement-035", "Cavoren", "country-008", "region-avarra-crescent", SettlementType::NormalCity, "normal_city", "Grassland market city serving horse, livestock and grain routes"},
    SettlementContent{"settlement-042", "Jalenen", "country-009", "region-avarra-crescent", SettlementType::NormalCity, "normal_city", "Industrial river-corridor city with rail yards and worker districts"},
    SettlementContent{"settlement-049", "Qorinen", "country-010", "region-avarra-crescent", SettlementType::NormalCity, "normal_city", "Temple-valley city balancing heritage streets and civic services"},
    SettlementContent{"settlement-056", "Xarinen", "country-011", "region-avarra-crescent", SettlementType::NormalCity, "normal_city", "Rain-fed forest gateway linked by hill roads and trail services"},
    SettlementContent{"settlement-063", "Evarais", "country-012", "region-avarra-crescent", SettlementType::NormalCity, "normal_city", "Salt-coast city with fishing markets, cold stores and storm shelters"},
    SettlementContent{"settlement-070", "Lurais", "country-013", "region-avarra-crescent", SettlementType::NormalCity, "normal_city", "Lake-basin city with water management, education and observatories"},
    SettlementContent{"settlement-077", "Sorenis", "country-014", "region-avarra-crescent", SettlementType::NormalCity, "normal_city", "Desert-edge caravan city with shaded markets and water depots"},
    SettlementContent{"settlement-084", "Zavelis", "country-015", "region-avarra-crescent", SettlementType::NormalCity, "normal_city", "Island-facing royal city with ferry piers and coastal promenades"},
    SettlementContent{"settlement-091", "Girelor", "country-016", "region-avarra-crescent", SettlementType::NormalCity, "normal_city", "Mountain-pass logistics city connecting roads, rail and freight"},
    SettlementContent{"settlement-092", "Ashagaon", "country-001", "region-avarra-crescent", SettlementType::Village, "village", "Riverbank farming village with a market-day square"},
    SettlementContent{"settlement-099", "Himagaon", "country-002", "region-avarra-crescent", SettlementType::Village, "village", "Dry-hill village with a shared water tank and orchard plots"},
    SettlementContent{"settlement-106", "Oshagaon", "country-003", "region-avarra-crescent", SettlementType::Village, "village", "Canal-side village with boat landing and fish stalls"},
    SettlementContent{"settlement-113", "Vinagaon", "country-004", "region-avarra-crescent", SettlementType::Village, "village", "Terraced farming village with a hill-road service stop"},
    SettlementContent{"settlement-120", "Cirapur", "country-005", "region-avarra-crescent", SettlementType::Village, "village", "Coastal craft village with a storm-safe community hall"},
    SettlementContent{"settlement-127", "Jorapur", "country-006", "region-avarra-crescent", SettlementType::Village, "village", "Delta village connected by road, footbridge and local ferry"},
    SettlementContent{"settlement-134", "Qumapur", "country-007", "region-avarra-crescent", SettlementType::Village, "village", "Quarry foothill village with dust-control and worker safety services"},
    SettlementContent{"settlement-141", "Xirapur", "country-008", "region-avarra-crescent", SettlementType::Village, "village", "Grassland village with a livestock market and veterinary access"},
    SettlementContent{"settlement-148", "Eshavale", "country-009", "region-avarra-crescent", SettlementType::Village, "village", "River-corridor village with a bus stop and repair workshop"},
    SettlementContent{"settlement-155", "Lumavale", "country-010", "region-avarra-crescent", SettlementType::Village, "village", "Temple-valley village with a heritage square and school"},
    SettlementContent{"settlement-162", "Savavale", "country-011", "region-avarra-crescent", SettlementType::Village, "village", "Forest-edge village with firebreaks and hill-road access"},
    SettlementContent{"settlement-169", "Ziravale", "country-012", "region-avarra-crescent", SettlementType::Village, "village", "Fishing village with a salt-market shed and cyclone refuge"},
    SettlementContent{"settlement-176", "Garonadi", "country-013", "region-avarra-crescent", SettlementType::Village, "village", "Lake village with landing steps and water-quality monitoring"},
    SettlementContent{"settlement-183", "Nalanadi", "country-014", "region-avarra-crescent", SettlementType::Village, "village", "Caravan-route village with a shaded rest yard and water point"},
    SettlementContent{"settlement-190", "Ushanadi", "country-015", "region-avarra-crescent", SettlementType::Village, "village", "Island-facing village with a ferry pier and boat-repair shed"},
    SettlementContent{"settlement-197", "Belakhet", "country-016", "region-avarra-crescent", SettlementType::Village, "village", "Mountain-pass village with a road-maintenance and rescue post"},
    SettlementContent{"settlement-202", "Marenvale", "country-017", "region-avarra-crescent", SettlementType::Village, "village", "Blue-cliff grove village with slope-safe footpaths"},
    SettlementContent{"settlement-203", "Meskopur", "country-018", "region-avarra-crescent", SettlementType::Village, "village", "Free-trade port village with a small customs and market quay"},
    SettlementContent{"settlement-204", "Arqakhet", "country-019", "region-avarra-crescent", SettlementType::Village, "village", "Volcanic-foothill village with hazard shelters and mineral-work safety"},
    SettlementContent{"settlement-205", "Vensarpara", "country-020", "region-avarra-crescent", SettlementType::Village, "village", "Southern-bay village with a fishing pier and naval supply access"},
}};

constexpr std::array<std::string_view, 33> kServices0{{
    "housing_districts",
    "public_market",
    "grocery_and_general_stores",
    "barber_shop",
    "clothing_and_personal_care",
    "restaurants_and_food_stalls",
    "clinic",
    "pharmacy",
    "school",
    "police_station",
    "fire_station",
    "vehicle_mechanic",
    "fuel_or_charging",
    "potable_water",
    "electricity",
    "sanitation_and_sewer",
    "solid_waste_collection",
    "storm_drainage",
    "public_transit_stop",
    "park_or_public_square",
    "civic_service_counter",
    "regional_hospital",
    "college_or_training_centre",
    "rail_or_ferry_terminal",
    "intercity_bus_terminal",
    "freight_market",
    "national_government_quarter",
    "teaching_hospital",
    "university",
    "international_airport",
    "central_rail_terminal",
    "river_ferry_terminal",
    "freight_yard",
}};

constexpr std::array<std::string_view, 26> kServices1{{
    "housing_districts",
    "public_market",
    "grocery_and_general_stores",
    "barber_shop",
    "clothing_and_personal_care",
    "restaurants_and_food_stalls",
    "clinic",
    "pharmacy",
    "school",
    "police_station",
    "fire_station",
    "vehicle_mechanic",
    "fuel_or_charging",
    "potable_water",
    "electricity",
    "sanitation_and_sewer",
    "solid_waste_collection",
    "storm_drainage",
    "public_transit_stop",
    "park_or_public_square",
    "civic_service_counter",
    "regional_hospital",
    "college_or_training_centre",
    "rail_or_ferry_terminal",
    "intercity_bus_terminal",
    "freight_market",
}};

constexpr std::array<std::string_view, 21> kServices2{{
    "housing_districts",
    "public_market",
    "grocery_and_general_stores",
    "barber_shop",
    "clothing_and_personal_care",
    "restaurants_and_food_stalls",
    "clinic",
    "pharmacy",
    "school",
    "police_station",
    "fire_station",
    "vehicle_mechanic",
    "fuel_or_charging",
    "potable_water",
    "electricity",
    "sanitation_and_sewer",
    "solid_waste_collection",
    "storm_drainage",
    "public_transit_stop",
    "park_or_public_square",
    "civic_service_counter",
}};

constexpr std::array<std::string_view, 16> kServices3{{
    "safe_housing",
    "potable_water_point",
    "electricity_or_microgrid",
    "toilets_and_sanitation",
    "waste_collection_point",
    "primary_school",
    "community_hall",
    "clinic_outreach",
    "emergency_response_access",
    "all_weather_road",
    "bus_or_shared_van_stop",
    "weekly_market",
    "mobile_barber_service",
    "grocery_kiosk",
    "small_repairs",
    "drainage_and_flood_route",
}};

constexpr std::array<FacilityProfileContent, 4> kFacilityProfiles{{
    FacilityProfileContent{"capital", kServices0},
    FacilityProfileContent{"major_city", kServices1},
    FacilityProfileContent{"normal_city", kServices2},
    FacilityProfileContent{"village", kServices3},
}};

constexpr std::array<std::string_view, 36> kRoadAccess{{
    "settlement-001",
    "settlement-002",
    "settlement-003",
    "settlement-007",
    "settlement-014",
    "settlement-021",
    "settlement-028",
    "settlement-035",
    "settlement-042",
    "settlement-049",
    "settlement-056",
    "settlement-063",
    "settlement-070",
    "settlement-077",
    "settlement-084",
    "settlement-091",
    "settlement-092",
    "settlement-099",
    "settlement-106",
    "settlement-113",
    "settlement-120",
    "settlement-127",
    "settlement-134",
    "settlement-141",
    "settlement-148",
    "settlement-155",
    "settlement-162",
    "settlement-169",
    "settlement-176",
    "settlement-183",
    "settlement-190",
    "settlement-197",
    "settlement-202",
    "settlement-203",
    "settlement-204",
    "settlement-205",
}};

constexpr std::array<std::string_view, 4> kRouteEndpoints0{{
    "settlement-001",
    "settlement-002",
    "settlement-003",
    "settlement-091",
}};

constexpr std::array<std::string_view, 3> kRouteEndpoints1{{
    "settlement-001",
    "settlement-021",
    "settlement-003",
}};

constexpr std::array<std::string_view, 3> kRouteEndpoints2{{
    "settlement-001",
    "settlement-002",
    "settlement-003",
}};

constexpr std::array<ConnectivityRouteContent, 3> kRoutes{{
    ConnectivityRouteContent{"rail", "Avarra Central Corridor", kRouteEndpoints0},
    ConnectivityRouteContent{"water", "River-to-Inland-Sea Ferry", kRouteEndpoints1},
    ConnectivityRouteContent{"air", "Avarra Regional Air Loop", kRouteEndpoints2},
}};

constexpr std::array<AirportRoleContent, 3> kAirports{{
    AirportRoleContent{"settlement-001", "international_gateway"},
    AirportRoleContent{"settlement-002", "coastal_international_and_domestic"},
    AirportRoleContent{"settlement-003", "regional_inland_sea_airport"},
}};

} // namespace

const RegionContent& avarra_baseline_design() noexcept {
    static const RegionContent region{
        "region-avarra-crescent",
        "Avarra Crescent",
        1U,
        false,
        true,
        std::span<const CountryContent>{kCountries},
        std::span<const SettlementContent>{kSettlements},
        std::span<const FacilityProfileContent>{kFacilityProfiles},
        std::span<const std::string_view>{kRoadAccess},
        std::span<const ConnectivityRouteContent>{kRoutes},
        std::span<const AirportRoleContent>{kAirports},
    };
    return region;
}

bool has_service(const RegionContent& region, std::string_view facility_profile_id, std::string_view service_id) noexcept {
    const auto profile = std::find_if(region.facility_profiles.begin(), region.facility_profiles.end(),
        [facility_profile_id](const FacilityProfileContent& candidate) { return candidate.id == facility_profile_id; });
    if (profile == region.facility_profiles.end()) {
        return false;
    }
    return std::find(profile->services.begin(), profile->services.end(), service_id) != profile->services.end();
}

} // namespace indoru::world::content
