#!/usr/bin/env python3
"""Generate a dependency-free C++ view of the Avarra design manifest."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "data/region-baselines/avarra-crescent.json"
OUTPUT = ROOT / "engine/cpp/src/avarra_region_content.cpp"
TYPE_NAMES = {
    "capital": "Capital",
    "major_city": "MajorCity",
    "normal_city": "NormalCity",
    "village": "Village",
}


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def array_block(name: str, cpp_type: str, values: list[str]) -> list[str]:
    lines = [f"constexpr std::array<{cpp_type}, {len(values)}> {name}{{{{"]
    lines.extend(f"    {value}," for value in values)
    lines.append("}};")
    return lines


def resolve_services(profiles: dict, profile_id: str, seen: set[str] | None = None) -> list[str]:
    seen = seen or set()
    if profile_id in seen:
        raise ValueError(f"facility profile inheritance cycle at {profile_id}")
    if profile_id not in profiles:
        raise ValueError(f"unknown facility profile: {profile_id}")
    seen.add(profile_id)
    profile = profiles[profile_id]
    inherited = resolve_services(profiles, profile["inherits"], seen) if profile.get("inherits") else []
    return list(dict.fromkeys(inherited + profile.get("additional", [])))


def generate() -> str:
    data = json.loads(INPUT.read_text(encoding="utf-8"))
    lines = [
        "// Generated by scripts/generate_avarra_cpp.py; do not edit by hand.",
        '#include "indoru/region_content.hpp"',
        "",
        "#include <algorithm>",
        "#include <array>",
        "",
        "namespace indoru::world::content {",
        "namespace {",
        "",
    ]

    country_values = [
        "CountryContent{" + ", ".join(cpp_string(c[k]) for k in ("countryId", "name", "regionCode", "flagId", "flagAsset")) + "}"
        for c in data["countries"]
    ]
    lines.extend(array_block("kCountries", "CountryContent", country_values))
    lines.append("")

    settlement_values = []
    for settlement in data["settlements"]:
        settlement_type = TYPE_NAMES.get(settlement["type"])
        if settlement_type is None:
            raise ValueError(f"unknown settlement type: {settlement['type']}")
        values = [
            settlement["settlementId"],
            settlement["name"],
            settlement["countryId"],
            settlement["regionId"],
            f"SettlementType::{settlement_type}",
            settlement["facilityProfileId"],
            settlement["role"],
        ]
        settlement_values.append(
            "SettlementContent{" + ", ".join(
                value if value.startswith("SettlementType::") else cpp_string(value)
                for value in values
            ) + "}"
        )
    lines.extend(array_block("kSettlements", "SettlementContent", settlement_values))
    lines.append("")

    resolved = {
        profile_id: resolve_services(data["facilityProfiles"], profile_id)
        for profile_id in data["facilityProfiles"]
    }
    for index, (profile_id, services) in enumerate(resolved.items()):
        values = [cpp_string(service) for service in services]
        lines.extend(array_block(f"kServices{index}", "std::string_view", values))
        lines.append("")

    profile_values = [
        "FacilityProfileContent{" + cpp_string(profile_id) + f", kServices{index}" + "}"
        for index, profile_id in enumerate(resolved)
    ]
    lines.extend(array_block("kFacilityProfiles", "FacilityProfileContent", profile_values))
    lines.append("")

    road_values = [cpp_string(settlement_id) for settlement_id in data["connectivity"]["roadAccessSettlementIds"]]
    lines.extend(array_block("kRoadAccess", "std::string_view", road_values))
    lines.append("")

    route_values = []
    route_index = 0
    for mode, key in (("rail", "railLines"), ("water", "waterRoutes"), ("air", "airLinks")):
        for route in data["connectivity"][key]:
            endpoints = [cpp_string(value) for value in route["settlementIds"]]
            lines.extend(array_block(f"kRouteEndpoints{route_index}", "std::string_view", endpoints))
            route_values.append(
                "ConnectivityRouteContent{" + ", ".join([
                    cpp_string(mode), cpp_string(route["name"]), f"kRouteEndpoints{route_index}"
                ]) + "}"
            )
            route_index += 1
            lines.append("")
    lines.extend(array_block("kRoutes", "ConnectivityRouteContent", route_values))
    lines.append("")

    airport_values = [
        "AirportRoleContent{" + cpp_string(airport["settlementId"]) + ", " + cpp_string(airport["role"]) + "}"
        for airport in data["connectivity"]["airportRoles"]
    ]
    lines.extend(array_block("kAirports", "AirportRoleContent", airport_values))
    lines.extend([
        "",
        "} // namespace",
        "",
        "const RegionContent& avarra_baseline_design() noexcept {",
        "    static const RegionContent region{",
        f"        {cpp_string(data['regionId'])},",
        f"        {cpp_string(data['regionName'])},",
        f"        {data['buildOrder']}U,",
        f"        {'true' if data['runtimeIntegrated'] else 'false'},",
        f"        {'true' if data['mappingReview']['status'] == 'proposed' else 'false'},",
        "        std::span<const CountryContent>{kCountries},",
        "        std::span<const SettlementContent>{kSettlements},",
        "        std::span<const FacilityProfileContent>{kFacilityProfiles},",
        "        std::span<const std::string_view>{kRoadAccess},",
        "        std::span<const ConnectivityRouteContent>{kRoutes},",
        "        std::span<const AirportRoleContent>{kAirports},",
        "    };",
        "    return region;",
        "}",
        "",
        "bool has_service(const RegionContent& region, std::string_view facility_profile_id, std::string_view service_id) noexcept {",
        "    const auto profile = std::find_if(region.facility_profiles.begin(), region.facility_profiles.end(),",
        "        [facility_profile_id](const FacilityProfileContent& candidate) { return candidate.id == facility_profile_id; });",
        "    if (profile == region.facility_profiles.end()) {",
        "        return false;",
        "    }",
        "    return std::find(profile->services.begin(), profile->services.end(), service_id) != profile->services.end();",
        "}",
        "",
        "} // namespace indoru::world::content",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    source = generate()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(source, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)} from {INPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
